### ISSUE TITLE
Support for systemd-timesyncd

### ISSUE THREAD

**Issue by eliasp** [saltstack-formulas/ntp-formula#14]
Support for `systemd-timesyncd` should be implemented for client-only setups where NTP server functionality isn't required:
- Check, whether the latest available systemd version is `>=216` [*]
- Ensure, the latest (`>=216`) version is installed
- Disable other implementation/services providing NTP client functionality
- Enable `systemd-timesyncd` (`timedatectl set-ntp 1`) [**]

[*] The reason for wanting `>=216` is, that since this release the whole NTP handling in systemd was streamlined. Before that, individual NTP services could provide drop-in configs which would then be used by systemd. This was quite a mess and error-prone. See also this entry from the [`NEWS`](http://cgit.freedesktop.org/systemd/systemd/tree/NEWS) file:

```
CHANGES WITH 216:

        * timedated no longer reads NTP implementation unit names from
          /usr/lib/systemd/ntp-units.d/*.list. Alternative NTP
          implementations should add a

            Conflicts=systemd-timesyncd.service

          to their unit files to take over and replace systemd's NTP
          default functionality.
```

[**] Once https://github.com/saltstack/salt/issues/20392 is implemented, the whole `timedatectl` setup should be done via DBus which provides a proper interface for this instead of fiddling with `cmd.run` output/results.

**Comment by aboe76** [comment]
@eliasp shouldn't that be in a different formula?

**Comment by eliasp** [comment]
As it serves the same purpose as any other NTP client (and might even replace existing NTP setups on many clients in the near future) I felt like the ntp-formula would be the best place to handle this to just abstract "timekeeping" without relying on a specific implementation of it.

**Comment by aboe76** [comment]
I can understand, but I prefer a clean relationship between formula name and what it does. Timesyncd is a different beast

**Comment by aboe76** [comment]
see systemd-formula
